import { Component, input } from '@angular/core';
import {
  LucideGlobe,
  LucideLayoutDashboard,
  LucideSmartphone,
  LucideApple,
  LucideCpu,
  LucideMegaphone,
  LucideBot,
  LucideMonitor,
  LucideServer,
  LucideDatabase,
  LucideCloud,
  LucideBrainCircuit,
  LucideStethoscope,
  LucideGraduationCap,
  LucideFactory,
  LucideShoppingBag,
  LucideWheat,
  LucideLandmark,
  LucideBuilding2,
  LucideConciergeBell,
  LucideHardHat,
  LucideRocket,
  LucideMenu,
  LucideX,
  LucideSun,
  LucideMoon,
  LucidePhone,
  LucideMail,
  LucideMapPin,
  LucideMessageCircle,
  LucideCheck,
  LucideCircleCheck,
  LucideStar,
  LucideChevronDown,
  LucideChevronUp,
  LucideArrowRight,
  LucideQuote,
  LucideUsers,
  LucideCalendar,
  LucideClipboardCheck,
  LucideShieldCheck,
  LucideZap,
  LucideHeadphones,
  LucideSearchCheck,
  LucideLock,
  LucideLayers,
  LucideSend,
} from '@lucide/angular';

@Component({
  selector: 'app-icon',
  imports: [
    LucideGlobe,
    LucideLayoutDashboard,
    LucideSmartphone,
    LucideApple,
    LucideCpu,
    LucideMegaphone,
    LucideBot,
    LucideMonitor,
    LucideServer,
    LucideDatabase,
    LucideCloud,
    LucideBrainCircuit,
    LucideStethoscope,
    LucideGraduationCap,
    LucideFactory,
    LucideShoppingBag,
    LucideWheat,
    LucideLandmark,
    LucideBuilding2,
    LucideConciergeBell,
    LucideHardHat,
    LucideRocket,
    LucideMenu,
    LucideX,
    LucideSun,
    LucideMoon,
    LucidePhone,
    LucideMail,
    LucideMapPin,
    LucideMessageCircle,
    LucideCheck,
    LucideCircleCheck,
    LucideStar,
    LucideChevronDown,
    LucideChevronUp,
    LucideArrowRight,
    LucideQuote,
    LucideUsers,
    LucideCalendar,
    LucideClipboardCheck,
    LucideShieldCheck,
    LucideZap,
    LucideHeadphones,
    LucideSearchCheck,
    LucideLock,
    LucideLayers,
    LucideSend,
  ],
  templateUrl: './icon.html',
  styleUrl: './icon.css',
})
export class Icon {
  readonly name = input.required<string>();
  readonly klass = input<string>('w-5 h-5', { alias: 'class' });
}
